### ISSUE TITLE
support ipython 3 and nbformat v4

### ISSUE THREAD

**Issue by aaren** [aaren/notedown#13]
Presently notedown requires ipython 1 or 2 to work. Version 3 uses a new
notebook format (the v4 notebook) that I haven't got around to implementing.

**Comment by jni** [comment]
:+1: !!! =(

**Comment by aaren** [comment]
Now using (and requiring) ipython 3 and using the v4 notebook format. Can still read any older notebook format, but all notebooks written out will be v4.

**Comment by stefanv** [comment]
:+1:
