### ISSUE TITLE
ipymd functionality: feedback wanted

### ISSUE THREAD

**Issue by aaren** [aaren/notedown#22]
@jni, @stefanv maybe you can test this out and give some feedback? 

I've just pushed a change to master that lets you use markdown files as the on disk notebook storage, editing them with the web notebook. This was inspired by [ipymd] which lets you do a similar thing.

This isn't documented yet but I've released it with 1.4.4.

To try it out, add the following to `ipython_notebook_config.py` in your ipython profile (probably `~/.ipython/profile_default/`):

    c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'

and then try opening up, editing and saving some markdown in the browser.

Unlike [ipymd], notedown preserves prompt numbers and outputs (using json code cells) in the markdown. This isn't very pretty but I get around it by collapsing json cells in my editor (and turning wrap off!).

[ipymd]: https://github.com/rossant/ipymd

**Comment by jni** [comment]
@aaren Cool functionality but not actually something I'm really looking for right now — we're using notedown *precisely* to avoid editing in the web notebook! I don't have the bandwidth right now to test it out... Best of luck!

**Comment by stefanv** [comment]
Is this likely to break with future releases of IPython, or is 
this kind of storage mechanism supported?  If reliable and stable, 
that would be a novel alternative!

**Comment by aaren** [comment]
@stefanv Support was added for this following https://github.com/ipython/ipython/issues/7222, so it has been a conscious decision to allow this to happen. I'm subclassing the API and didn't need to change too much so hopefully can keep up to date. Should be ok for 3.x anyway.

@jni I still work largely in my text editor. I do still find the notebook useful for code interaction and plotting figures though. This allows me to edit a file with both the browser and my editor at once: I can be editing in vim, then drop into the browser and create some figures, then return to vim and keep editing without worrying about merging the figures in.

**Comment by jni** [comment]
@aaren I see! That's a pretty nice use-case. I'll let you know when I try it out! =)

**Comment by rossant** [comment]
hi @aaren , I'm just discovering this, it's a cool project!
Just a side note: ipymd *can* preserve text output (that's an option you can enable). The input prompts are reset to the normal order however (I have no use for nonlinear input prompts myself). Finally I'd like to implement saving inline plots automatically in external files and include them in Markdown.

**Comment by aaren** [comment]
@rossant, thanks :) and thanks for solving the markdown storage problem in ipymd!

Yes, storing the outputs in a more markdowny way would be good. I couldn't think of a satisfactory schema for it though and just decided to copy them as is (json).

We could probably solve the limited case of text or image outputs, but I'm not sure about the general case. Storing images in external files and linking to them would be good. Have a look at `notedown --render` - this converts images to data URIs (but these don't render on github).

**Comment by aaren** [comment]
Seems to be working fine for me so far.
