### ISSUE TITLE
Option --match not-fenced

### ISSUE THREAD

**Issue by asimjalis** [aaren/notedown#25]
It would be nice to have a "--match indented". In other words, the opposite of "--match fenced". 

Benefits are:

1. Easy to indicate syntax of non-executable code (using fencing) so IPYN syntax highlighting can work.

2. Easy to distinguish executable vs non-executable code.

**Comment by aaren** [comment]
So `notedown --match indented` would only execute indented code and would leave fenced code as-is in a markdown cell?

**Comment by aaren** [comment]
You can already do `notedown --match strict`, which requires executed code to have `.input` in the classes, e.g.

    ```
    not executed
    ```

    ```{.input}
    executed
    ```

    ```{.python}
    not executed
    ```

    ```{.python .input}
    executed
    ```

**Comment by aaren** [comment]
Not going to add this unless there is more demand and the current solution (`--match strict`) is insufficient.
