### ISSUE TITLE
Compatibility with ipython/jupyter 4.0

### ISSUE THREAD

**Issue by lgautier** [aaren/notedown#26]
I am unable to get `--render` to work. This seems to be because of backward incompatible changes in ipython/jupyter.

**Comment by aaren** [comment]
Thanks. I'm pretty busy so this might be unresolved for a few days.

**Comment by aaren** [comment]
I've cut release 1.4.5 that restricts ipython to < 4.

https://pypi.python.org/pypi/notedown/1.4.5

**Comment by aaren** [comment]
Any help on this is welcome!

Current test failure is on `MarkdownExporter`, which needs a `Configurable` parent trait. I don't know how to set this currently.

**Comment by aaren** [comment]
I'm working on this in #31. I've got it passing tests, just need to put back in compatibility with IPython 3.

**Comment by aaren** [comment]
closed by #31
