### ISSUE TITLE
Fenced code blocks: Compatibility with pandoc

### ISSUE THREAD

**Issue by nthiery** [aaren/notedown#29]
When converting Rst to markdown, and writing a fenced code block,
`pandoc` insert a space between the triple quotes and the options:

    mistral-/tmp>cat bla.rst 
    .. code:: python

        1+1

    mistral-/tmp>pandoc bla.rst -t markdown
    ``` {.sourceCode .python}
    1+1
    ```

However, when converting this further to a notebook, `notedown` seems
to get confused by this additional space, and does not produce a block
as desired.

Sorry, that later part is not super specific. I'll provide a complete
example later on, but right now I broke notedown on my machine while
hacking around ...

Would it be possible to tweak notedown's regexp to tolerate this
additional space?

Btw: thanks a lot for notedown! That's going to be super useful in my
Rst -> notebook workflow!

**Comment by aaren** [comment]
Should be a simple change to the regex. I'll fix next week. Thanks for  reporting!

**Comment by nthiery** [comment]
On Thu, Sep 17, 2015 at 04:38:53AM -0700, aaren wrote:
>    Should be a simple change to the regex. I'll fix next week. Thanks for
>    reporting!

Great, looking forward to it. Thanks in advance!

				Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by aaren** [comment]
I think that should have fixed your problem. Please say if not.

**Comment by nthiery** [comment]
Working beautifully! That's open source in action :-)
Thanks much.
