### ISSUE TITLE
notedown: command not found

### ISSUE THREAD

**Issue by toomey8** [aaren/notedown#30]
I'm on OSX 10.10.3 (Yosemite) 

* Python version / location

> ~> python -V
> Python 2.7.10 :: Anaconda 2.3.0 (x86_64)
> ~> which python
> //anaconda/bin/python

* iPython version / location

> ~> which ipython
> //anaconda/bin/ipython
> ~> ipython -V
> 3.2.0

* notedown

> pip install note down

Appears to work fine, and installs at:

> /anaconda/lib/python2.7/site-packages

> import notedown

Works fine within ipython

But when I try to call notedown I get an error:

> -bash: notedown: command not found

Any ideas on how to fix this? Deep thanks!

**Comment by aaren** [comment]
Not sure about this one. I don't have a mac to test it. 

What does 

```python
import notedown
notedown.__file__
```

give you?

**Comment by toomey8** [comment]
thanks for responding! I get:

    AttributeError: 'module' object has no attribute

**Comment by aaren** [comment]
Thats odd. Have you tried `pip uninstall notedown; pip install notedown`?

**Comment by toomey8** [comment]
Unfortunately, that doesn't work. I'll have someone else with a mac install it so I can see if it's my environment and write back. I un and then reinstalled anaconda as as well. Thanks!

**Comment by aaren** [comment]
Closing for now as I'm guessing it was an environment problem. Can reopen if you have more details.
