### ISSUE TITLE
optionally strip outputs when saving markdown notebook from ipython

### ISSUE THREAD

**Issue by amcpherson** [aaren/notedown#44]
Not sure of the ideal mechanism for setting this, but would be nice to be able to save a markdown without outputs from within ipython, allowing for seamless use of git without polluting repo with output noise (text encoded images etc).

**Comment by aaren** [comment]
Just checking I understand: you'd like to be able to edit a markdown notebook and play around with figures, but *not* have the figure info saved in the markdown source, only the changes to code / markdown?

I can certainly see the benefit of that. Does this PR work for you?

**Comment by amcpherson** [comment]
I have been using it for a couple days and it works fine so far.

**Comment by 153957** [comment]
Fixed in #46
