### ISSUE TITLE
support of cell metadata in markdown

### ISSUE THREAD

**Issue by cleemesser** [aaren/notedown#59]
I am interested in supporting notebook cell metadata in the markdown file.This would have benefits:
- It would maintain metadata like slideshow information for cells and allow one to write a slide show in markdown originally.
- The would allow true round trip fidelity ipynb -> markdown -> ipynb

I am not sure about the best way to do this, but I can imagine abusing markdown links somewhat

each markdown cell would be allowed to have a "comment:"
<pre>
[//]: # ( "cell_type": "markdown", "metadata": { "slideshow": { "slide_type": "slide"} } )
### The markdown content level three header
content plain text...
</pre>

The code blocks would be handled as they are in notedown, but would add an optional metadata tag:
<pre>
```{.python, "metadata" : {"collapsed": false, "slideshow": { "slide_type": "fragment"} } }
import numpy, pandas
y = 3 * 4
```
</pre>

This may be an answer to #47
I am not married to the idea of using this particular system, but it would seem it would be ignored by a typical common-mark/markdown renderer and would not be too hard to implement.

**Comment by sje30** [comment]
hi @cleemesser - I have other reasons for working on this project (supporting Julia, R), so roundtripping sounds like a great idea to me.  joint project?!?

**Comment by sje30** [comment]
p.s. you know more python than me!

**Comment by cleemesser** [comment]
Sounds good. I have forked aaren's code and am messing with it as a prototype.

**Comment by aaren** [comment]
I'm not really sure about the best way to do this, and I'm a bit reluctant as I have very little time to maintain this any more, but things to consider are Pandoc's `header_attributes` and `fenced_divs` http://pandoc.org/MANUAL.html

Closing for now.
